<!--
/**
 * Product Question
 * Modal window content
 *
 * @category Internship
 * @package Internship\ProductQuestion
 * @author Andrii Tomkiv <tomkivandrii18@gmail.com>
 * @copyright 2024 Tomkiv
 */
-->
<button type="button" class="action primary tocart" id="question-button" data-toggle="modal"
            data-target="product-question-modal"><?= __('Ask Question')?></button>

<div class="modal fade" id="product-question-modal" role="dialog" style="display:none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?= __('Ask Question')?></h4>
            </div>
            <div class="modal-body">
                <form name="question-form">
                    <div class="form-group" style="margin-top: 15px">
                        <label for="name"><?= __('Name'); ?>:</label>
                        <input type="text" class="form-control" id="name" placeholder="Enter name" name="name">
                        <div class="name-hint" style="display:none;">
                            <h5>Name should be entered</h5>
                        </div>
                    </div>
                    <div class="form-group" style="margin-top: 15px">
                        <label for="email"><?= __('Email'); ?>:</label>
                        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
                        <div class="email-hint" style="display:none;">
                            <h5>Email should be entered</h5>
                        </div>
                    </div>
                    <div class="form-group" style="margin-top: 15px">
                        <label for="question"><?= __('Question'); ?>:</label>
                        <input type="text" class="form-control" name="question" id="question"
                               placeholder="Ask your question here..." />
                        <div class="question-hint" style="display:none;">
                            <h5>Question should be entered</h5>
                        </div>
                    </div>
                    <div style="margin-top: 15px">
                        <input type="submit" class="action primary tocart" id="submit-question" value="Send"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Internship_ProductQuestion/js/product-question-component" : {}
        }
    }
</script>
